export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';

export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_REMOVE_SUCCESS = 'USER_REMOVE_SUCCESS';

export const AUTH_ACTION_START = 'AUTH_ACTION_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_ASYNC_ERROR = 'ADD_ASYNC_ERROR';
export const REMOVE_ASYNC_ERROR = 'REMOVE_ASYNC_ERROR';
