export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_REMOVE_SUCCESS = 'USER_REMOVE_SUCCESS';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_ASYNC_ERROR = 'ADD_ASYNC_ERROR';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
